development:
  bucket: goodnews.development
  access_key_id: 1JVDNWPQQXNRFNY08D82
  secret_access_key: kPfpu1RQxRW1nj+DLXSdDs9pzdEFhbBz4J3Z/WcP
  
test:
  bucket: goodnews.test
  access_key_id: 1JVDNWPQQXNRFNY08D82
  secret_access_key: kPfpu1RQxRW1nj+DLXSdDs9pzdEFhbBz4J3Z/WcP

production:
  bucket: goodnews.production
  access_key_id: 1JVDNWPQQXNRFNY08D82
  secret_access_key: kPfpu1RQxRW1nj+DLXSdDs9pzdEFhbBz4J3Z/WcP